''' The purpose of this file is to configure all of the
    settings for the game and thier interactions with functionality '''
# Size of main window
WIN_WIDTH = 1920
WIN_HEIGHT = 1080
# Defining size of each tile
TILESIZE = 64

# Colors
RED = (255,0,0)
BLACK = (0,0,0)
BLUE = (0,0,255)
GREEN = (0,255,255)
YELLOW = (0,255,0)
BROWN = (150,75,0)
GRAY = (128,128,128)
WHITE = (255,255,255)

# FrameRate of Game
FPS = 30
# Delay between movement registers (use higher hold delay with higher FPS)
HOLD_DELAY = 2

# Defining layers in the z axis
PLAYER_LAYER = 6
ENEMY_LAYER = 5
GROUND_LAYER4 = 4
GROUND_LAYER3 = 3
GROUND_LAYER2 = 2
GROUND_LAYER1 = 1

# Special Tiles
CHEST = (1408, 1152)
ENEMY = (576, 896)
DOOR = (576*2, 702*2)
OUTCROP = (704, 448)
                                              
PATH_9T_UL =   [(320,0   ),(1344,512),(960,128 ),(0,704   ),(192,1792),(1152,128),(192,704),(1152,512),(1536,512)]# PATH_9T_UL
PATH_9T_U =    [(384,0   ),(1408,512),(1024,128),(64,704  ),(256,1792),(1216,128),(256,704),(1216,512),(1600,512)]# PATH_9T_U
PATH_9T_UR =   [(448,0   ),(1472,512),(1088,128),(128,704 ),(320,1792),(1280,128),(320,704),(1280,512),(1664,512)]# PATH_9T_UR
PATH_9T_L =    [(320,64  ),(1344,576),(960,192 ),(0,768   ),(192,1856),(1152,192),(192,768),(1152,576),(1536,576)]# PATH_9T_L
PATH_9T_C =    [(384,64  ),(1408,576),(1024,192),(64,768  ),(256,1856),(1216,192),(256,768),(1216,576),(1600,576)]# PATH_9T_C
PATH_9T_R =    [(448,64  ),(1472,576),(1088,192),(128,768 ),(320,1856),(1280,192),(320,768),(1280,576),(1664,576)]# PATH_9T_R
PATH_9T_BL =   [(320,128 ),(1344,640),(960,256 ),(0,832   ),(192,1920),(1152,256),(192,832),(1152,640),(1536,640)]# PATH_9T_BL
PATH_9T_B =    [(384,128 ),(1408,640),(1024,256),(64,832  ),(256,1920),(1216,256),(256,832),(1216,640),(1600,640)]# PATH_9T_B
PATH_9T_BR =   [(448,128 ),(1472,640),(1088,256),(128,832 ),(320,1920),(1280,256),(320,832),(1280,640),(1664,640)]# PATH_9T_BR
PATH_4T_UL =   [(576,64  ),(1344,384),(1024,0  ),(64,576  ),(256,1664),(1216,0  ),(256,576),(1216,384),(1600,384)]# PATH_4T_UL
PATH_4T_UR =   [(512,64  ),(1408,384),(1088,0  ),(128,576 ),(320,1664),(1280,0  ),(320,576),(1280,384),(1664,384)]# PATH_4T_UR
PATH_4T_BL =   [(576,0   ),(1344,448),(1024,64 ),(64,640  ),(256,1728),(1216,64 ),(256,640),(1216,448),(1600,448)]# PATH_4T_BL
PATH_4T_BR =   [(512,0   ),(1408,448),(1088,64 ),(128,640 ),(320,1728),(1280,64 ),(320,640),(1280,448),(1664,448)]# PATH_4T_BR
PATH_ET_1 =    [(320,256 ),(1344,704),(960,320 ),(0,896   ),(192,1984),(1152,320),(0,896),(1152,704),(1536,704)]# PATH_ET_1
PATH_ET_2 =    [(384,256 ),(1408,704),(1024,320),(64,896  ),(256,1984),(1216,320),(64,896),(1216,704),(1600,704)]# PATH_ET_2
PATH_ET_3 =    [(448,256 ),(1472,704),(1088,320),(128,896 ),(320,1984),(1280,320),(128,896),(1280,704),(1664,704)]# PATH_ET_3
PATH_ED_1 =    [(1536,0 ),(1344,0  ),(960,0   ),(0,576   ),(192,1664),(1152,0  ),(192,576),(1152,384),(1536,384)]# PATH_ED_1
PATH_ED_2 =    [(1536,64 ),(1344,64 ),(960,64  ),(0,640   ),(192,1728),(1152,64 ),(192,640),(1152,448),(1536,448)]# PATH_ED_2

DETAIL_9T_UL = [(1536,128),(576 ,704),(1344,128),(512,1344),(384,1664),(1728,128),(576,704),(960 ,512),(768,128)]# DETAIL_9T_UL
DETAIL_9T_U =  [(1600,128),(640 ,704),(1408,128),(576,1344),(448,1664),(1792,128),(640,704),(1024,512),(832,128)]# DETAIL_9T_U
DETAIL_9T_UR = [(1664,128),(704 ,704),(1472,128),(640,1344),(512,1664),(1856,128),(704,704),(1088,512),(896,128)]# DETAIL_9T_UR
DETAIL_9T_L =  [(1536,192),(576 ,768),(1344,192),(512,1408),(384,1728),(1728,192),(576,768),(960 ,576),(768,192)]# DETAIL_9T_L
DETAIL_9T_C =  [(1600,192),(640 ,768),(1408,192),(576,1408),(448,1728),(1792,192),(640,768),(1024,576),(832,192)]# DETAIL_9T_C
DETAIL_9T_R =  [(1664,192),(704 ,768),(1472,192),(640,1408),(512,1728),(1856,192),(704,768),(1088,576),(896,192)]# DETAIL_9T_R
DETAIL_9T_BL = [(1536,256),(576 ,832),(1344,256),(512,1472),(384,1792),(1728,256),(576,832),(960 ,640),(768,256)]# DETAIL_9T_BL
DETAIL_9T_B =  [(1600,256),(640 ,832),(1408,256),(576,1472),(448,1792),(1792,256),(640,832),(1024,640),(832,256)]# DETAIL_9T_B
DETAIL_9T_BR = [(1664,256),(704 ,832),(1472,256),(640,1472),(512,1792),(1856,256),(704,832),(1088,640),(896,256)]# DETAIL_9T_BR
DETAIL_4T_UL = [(1600,0  ),(640 ,576),(1408,0  ),(704,1344),(448,1536),(1792,0  ),(640,576),(1024,384),(832,0)]# DETAIL_4T_UL
DETAIL_4T_UR = [(1664,0  ),(704 ,576),(1472,0  ),(768,1344),(512,1536),(1856,0  ),(704,576),(1088,384),(896,0)]# DETAIL_4T_UR
DETAIL_4T_BL = [(1600,64 ),(640 ,640),(1408,64 ),(704,1408),(448,1600),(1792,64 ),(640,640),(1024,448),(832,64)]# DETAIL_4T_BL
DETAIL_4T_BR = [(1664,64 ),(704 ,640),(1472,64 ),(768,1408),(512,1600),(1856,64 ),(704,640),(1088,448),(896,64)]# DETAIL_4T_BR
DETAIL_ET_1 =  [(576 ,256),(384 ,896),(1344,320),(512,1280),(384,1856),(1728,320),(576,896),(960 ,704),(768,320)]# DETAIL_ET_1
DETAIL_ET_2 =  [(576 ,320),(448 ,896),(1408,320),(576,1280),(448,1856),(1792,320),(640,896),(1024,704),(832,320)]# DETAIL_ET_2
DETAIL_ET_3 =  [(576 ,320),(512 ,896),(1472,320),(640,1280),(512,1856),(1856,320),(704,896),(1088,704),(896,320)]# DETAIL_ET_3
DETAIL_ED_1 =  [(640 ,448),(576 ,576),(1344,0  ),(704,1472),(384,1556),(1728,0  ),(576,576),(960 ,384),(768,0)]# DETAIL_ED_1
DETAIL_ED_2 =  [(704 ,448),(576 ,640),(1344,64 ),(768,1472),(384,1600),(1728,64 ),(576,640),(960 ,448),(768,64)]# DETAIL_ED_2
''' TILE KEY
A = PATH_9T_UL  || S = DETAIL_9T_UL || ! = Enemy
B = PATH_9T_U   || T = DETAIL_9T_U  || $ = Treasure/Loot Chest
C = PATH_9T_UR  || U = DETAIL_9T_UR || @ = Door 
D = PATH_9T_L   || V = DETAIL_9T_L  || * = Material Node
E = PATH_9T_C   || . = DETAIL_9T_C  ||
F = PATH_9T_R   || X = DETAIL_9T_R  || ABREVIATIONS: 
G = PATH_9T_BL  || Y = DETAIL_9T_BL || 9T = Nine Tile
H = PATH_9T_B   || Z = DETAIL_9T_B  || 4T = Four Tile
I = PATH_9T_BR  || 0 = DETAIL_9T_BR || UL = Upper Left (ext.)
J = PATH_4T_UL  || 1 = DETAIL_4T_UL || ET = Excess Tile
K = PATH_4T_UR  || 2 = DETAIL_4T_UR || ED = Excess Detail
L = PATH_4T_BL  || 3 = DETAIL_4T_BL || Array Indexes:
M = PATH_4T_BR  || 4 = DETAIL_4T_BR || 0=Spawn, 1=Meadows
N = PATH_EC_1   || 5 = DETAIL_EC_1  || 2=Plains, 3=Desert
O = PATH_EC_2   || 6 = DETAIL_EC_2  || 4=Swamp, 5=Mountains
P = PATH_EC_3   || 7 = DETAIL_EC_3  || 6=Beach, 7=VolcanicEdge
Q = PATH_ED_1   || 8 = DETAIL_ED_1  || 8=Castle                 '''
# Room0 TILEMAP (40x30)
ROOM_TILEMAP = [[],[],[],[],[],[],[],[],[]]

ROOM_TILEMAP[0] = [
    'STTTTTTTTTTTTTTTTTTTTTTTTTTTTTT4D@F3TTTU',
    'V.........................8....AMELC...X',
    'V..ABBBBBC..9.................AMEEELC..X',
    '4ABMEE$EELBBBBBBBBBBBBBBBBBBBBMEEEEEF..X',
    'BMEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEREF..X',
    '@EEEEEEEEEREEEEEEEEEEEEEEEEEEEEEEEEEF..X',
    'HKEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEF..X',
    '2GHKEEEEEJHHHHHHHHHHHHHHHHHHHHKEEEEEF..X',
    'V..GKEQEJI....................GKEEEJI..X',
    'V...DEEEF..........8...........DQEEF...X',
    'V...DEEEF..................9...DEEEF...X',
    'V...DEEEF....ABBBBBC...........DEEEF.8.X',
    'V...DEEEF....DEEEEEF...........DEEEF...X',
    'V...DEEEF9...DQEEEEF...........DEEEF...X',
    'V..AMEEELC...DEEEEEF...........DEEEF...X',
    'V..DREEEEF...DEEEEEF...........DEEEF...X',
    'V..DEEEEEF...DEEEEEF...........DEEEF...X',
    'V..DEEEEEF...GKEEEJI.....8.....DEERF...X',
    'V..DEE$EEF....DEEEF............DEEEF...X',
    'V..DEEEQEF....DEEEF............DEEEF...X',
    'V..GHHHHHI....DEEEF............DEEEF...X',
    'V..........8..DREEF............DEEEF...X',
    'VABBBBBC.....AMEEELC..........AMEEELC..X',
    'VDEEEEELBBBBBMEEEEELBBBBBBBBBBMEEEEEF..X',
    'VDEEEREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEF..X',
    'VDE$EEEEEEEEEEEEEEEEEEEEEEEEEEREEEE$F..X',
    'VDEEEEEEEEEEEEEEEEQEEEEEEEEEEEEEEEEEF..X',
    'VDEEEEEJHHHHHHKEEEJHHHHHHHHHHHKEEEEEF..X',
    'VGHHHHHI......GKEJI......8....GHHHHHI..X',
    'YZZZZZZZZZZZZZ2D@F1ZZZZZZZZZZZZZZZZZZZZ0',
]
# Room1 TILEMAP (51x31)
ROOM_TILEMAP[1] = [
    'STTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTU',
    'V..ABBBBBC..................ABBBBBC...............X',
    'V.AMEE$EELBBBBBBBBBBBBC...ABMEEEEELBC..ABBBBBBBC..X',
    'V.DEEEEEEEEEEEEEEEEEEEF...D$EEEEEEEELBBMEE*EEEELBC3',
    'V.DEEEEEEJHHHHHHHHHHKEF...DEEEE!EEEEEEEEEEEEEEEEELB',
    'V.D*EEEEEF..........DEF...GKEEEEEEEEEEEEEEE!EEEEEE@',
    'V.GKEEEEJI......ABBBMELBBBCGHK*EEEEEEEEEEEEEEEEEEJH',
    'V..GKEEEF.....ABM*EEEEEEEELBCGHHHHHHHHKEEEEEEEEEJI1',
    'V...DEEEF....AMEEEEEEEEEEEEELC........GHKEEEEEJHI.X',
    'V...DEEELBBBBMEEEEJHHHHHKEEEELC.........DEEEEEF...X',
    'V...DEEEEEEEEEEEEELBBBBBMEEEE$F.........GKEEEJI...X',
    'V...DEEEEEE!EEEEEEEE*E*EEEEEEEF..........DEEEF....X',
    'V...DEEEEEEEEEEEEEJHHHHHKEEEE$F..........DEEEF....X',
    'V...DEEEJHHHHKEEEELBBBBBMEEEEJI..........DEEEF....X',
    'V...DEEEF....GKEEEEEEEEEEEEEJI...........DEEEF....X',
    'V...DEEEF.....GHKEEEEEEEEEJHI............DEEEF....X',
    'V...DEEEF.......GHHHHHHHHHI..............DEEEF....X',
    'V...DEEEF...............................AMEEELC...X',
    'V...DEEEF........ABBBBC................AMEEEEELC..X',
    'V.ABMEEELBBBBBBBBME*EELBBBBBBBBBBBBBBBBMEEEEEEELBCX',
    'V.D*EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE*FX',
    'V.DEEE!EEEEEEEEEEEEEEEEEEEEEEEEEE!EEEEEEEEEEEE!EEFX',
    'V.DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFX',
    'V.GKEEJHHHKEEEEEJHHHHHHHKEEJKEEEEEEEEEJHHHK*EEEJHIX',
    'V..GHHI...GKE$EJI.......GHHIGKEEEEEEEJI...GHHHHI..X',
    'V..........GHHHI.............DEEEEEEEF............X',
    'V............................GKEEEEEJI............X',
    'V.............................DEEEEEF.............X',
    'V.............................DEEEEEF.............X',
    'V.............................GHKEJHI.............X',
    'YZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ2D@F1ZZZZZZZZZZZZZZ0',
]
# Room2 TILEMAP (70x40)
ROOM_TILEMAP[2] = [
    'STTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTU',
    'V..ABBCABBBBCABBBBBBBBC......ABBBBBC...ABBBBBBBBBBBBBBBBBBBBBBBBBBBBCX',
    '4ABMEEFDEEEEFDEE!EEEEELBBBBBBMEE$EELBBBMEEEEEEEEEEEEEEEEEEEEEEEEEE*EFX',
    'BMEEEELMEEEELMEEEEJKEEEEEEEEEEEOEEEEEEEEEEEEEEEEEOEEEEEEEEEEEEEEEEEEFX',
    '@EEEEEEEEEEOEEEEEJIDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEJKEEEEE*EEEEEEJKEEFX',
    'HKEEEEEEJHHKEEEEELBMEEJHHHHHHHHHHHHHHHHKEEE$EEEEEEFDEEJHHHHHHKEEFDEEFX',
    '2GHKEEEEF..DEJHHKEEEEEF................GHHHHHHHKEEFDEELBBBBBBMEEFDEEFX',
    'V..DEEEJIABMEFABMEEEEEF.......ABBBBBBBBBBBBBBBCDEEFD!EEEEEEEEE!EFDEEFX',
    'V..DEEELBMEEEFD$EEJKEELBBBBBBBMEEEEEEEEEEEEEEEFDEEFDEEEEEEEEEEEEFDEEFX',
    'V..DEEE!EEJKELMEEEFDEEEEOEEEEEEEEEEEEEEEEEEEEEFDEEFDEEJKEEEJKEEEFDEEFX',
    'V..DEEEEEELMEEEEEELMEEENEEEEEEEEEOEEEE!EEEEEEEFDEEFDEEFDEPEFDEEEFDEEFX',
    'V..DEEEEEEEEEEEEEEEEEEJHHHHHHHKEEEEEEEEEEEEEEEFDEEFDEEFDEEEFDEEEFDEEFX',
    'V..GHHHHHHHHHHHHHHHHHHI.......DEEEEEEEEEEEEE$EFDEELMEEFDEEEFDEEELMEEFX',
    'V..ABBBC...............ABBBC..DEEEEEEEEEEEEEEEFDEEEEEEFDEEEFD*EEEEEEFX',
    'V.AMEEELC.............AMEEELC.DEE!EEEEEEEEEEEEFDEEEEEEFDEEEFDEEE*EEEFX',
    'VAMEEEEELBBBBBBBBBBCABMEE$EELCDEEEEEEEEEEEEEEEFGHHHHHHIGKEJIGHHHHHHHIX',
    'VDEEEEEEEEE*EEEEEEELMEEEEEEEEFDEEEEEEEEEEEEEEEF.........DEF..........X',
    'VDE$EEEEEEEEEEEE!EEEEPEEEEEEEFGHHHHHKEEEJHHHHHI.......ABMELBBBBBC....X',
    'VDEEEEEEEEEEJKEEEEEEEEEEEEEEEF.....AMEEELC..........ABMEEEEEEEEELBC..X',
    'VGKEEEEEJHHHIGHHHHHHHHKEEEEEJI....AMEEEEELC........AMEEEEEEEEOEEEELC.X',
    'V.GKEEEJI.............GKEEEJI....AMEEEOEEELC......AMEEEEEJHHHKEEEEELC3',
    'V..DEEJI...............DEEEF.....DEEJHHHKEEF......DEEEEJHI...GHKEEEELB',
    'V..DEELC...............DEEEF.....DEELBBBMEEF......D$E!EF.......DEEEEE@',
    'V..GKE*F...............DEEJI.....DEEEEEEEEEF......DEEEELBC...ABMEEEEJH',
    'V...DEJI...............DEELC.....DEEE$EEEEEF......GKEEEEELBBBM*EEEEJI1',
    'V...DELC...............DEEEF.....DEEJHHHKEEF.......GKEEEEEEEEEEEEEJI.X',
    'V..AMEEF...............DE!EF.....DEELBBBMEEF........GHK*EEEEPEEEJHI..X',
    'V..D*EEF...............DEEEF.....GKEEEEEEEJI..........GHHHHHHHHHI....X',
    'V..DEEEF...............DEEEF......GKEEEEEJI..........................X',
    'V..DEEJI...............DEEEF.......GKEEEJI...........................X',
    'V..DEELC...............DEEEF........DE!EF............................X',
    'V.AMEEELC.............AMEEELC.......DEEEF............................X',
    'VAMEEEEELBCABBBC.ABBBBMEEEEELBBBCABBMEEELBBCABBCABBBBC...............X',
    'VDEEEEEEEELMEEELBMEEEEEEEEEEEEE*LMEEEEEEEEELMEELMEE*ELBBC............X',
    'VDE$EEENEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE*EENEEEEEEEEEEEEE*F............X',
    'VDEEEEEEEEEEEEEEEEEEENEEEEEEEEEEEEEEEEEEEEEEEEEEEEEJHHHHI............X',
    'VGKEEEEEJHHHHKEEEJHHHHKEEEEEJHHHHHHHHHHHHHHHHHHHHHHI.................X',
    'V.GK*EEJI....DEEEF....GK*EEJI........................................X',
    'V..GHHHI.....GKEJI.....GHHHI.........................................X',
    'YZZZZZZZZZZZZ2D@F1ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ0',
]
# Room3 TILEMAP (24x60)
ROOM_TILEMAP[3] = [
    'STTTTTTTTTTTTTTTTTTTTTTU',
    'VABBBBBBBBBBC.....ABBBCX',
    '4DEEEEEEE!EELC..ABMEEEFX',
    'BMEEEEEEEEEEEF.AMEEEE$FX',
    '@EEEEEEJKEEEEFAMEEEEEEFX',
    'HKEE*JHIGKEEELMEEEE!E$FX',
    '2DEEJI..AMEEEEEEEEEEEEFX',
    'VDEEF.ABMEEEEOEEEEEEEEFX',
    'VDEELBMEEEEEEEEEEEJHHHIX',
    'VDEOEEEEEEEEENEEEJI....X',
    'VDENEEEEEEEEEEEEJI.....X',
    'VDEEEEEEEEEEEEEJI......X',
    'VDEEEE!EEEEEEEEF.......X',
    'VDEEEEEEEEOEEEELC......X',
    'VGHKEEEEEEEEEEEELC.....X',
    'V..GHHKEEEEEEEEEELBBCACX',
    'V.....GHKEEEEEEEEEE*LMFX',
    'V.......GKEEEEEEEEEEEEFX',
    'V........GKEEEEEEEEEEEFX',
    'V.ABBBC...GKEEEEEEOEEEFX',
    'VAME$ELC...DEEE!EEEEEEFX',
    'VDEEEEELC..GKEEEEEEEEEFX',
    'VDEEEEE*F...DEEEEJK*EEFX',
    'VDEEEEOEF...DEEEJIGHHHIX',
    'VDEE!EEEF...DEEJI...ABMX',
    'VDEEEE*JI..AMEELC..AM$FX',
    'VDEEEEJI..AMEEEEF.AMEEFX',
    'VGKEEJI...DEEEEELCDEEEFX',
    'V.DEELC..AMEEEEEEFDEEEFX',
    'V.DEEELCAMEEEOEEEFDEEEFX',
    'V.GKEEELMEEEEEEEELMEEEFX',
    'V..GKEEEEEEEEEEEEEEEEEFX',
    'V...GKEEEEEEEEEEEEEP!EFX',
    'V...AMEEEEEEEEEEEEEEEEFX',
    'V..AMEEEEEENEEEEEEEEEEFX',
    'V..DEEEEEEEEEEEEE!EEEEFX',
    'V..DEEEEEEEEEJKEEEEEE*FX',
    'V.AMEEEEEEEEJIGKEEEEEEFX',
    'V.DEEEEEEEEEF..GHHK*EEFX',
    'V.D$EEEEEEEJIABBC.GHHHIX',
    'VAMEEOEEEEJIAME*LC.....X',
    'VDEEEEEEEELBMEEEELC....X',
    'VDEEENEEEEEEEEEEEEF....X',
    'VDEEEEEEEJHHKEEEE$F....X',
    'VDEEEEEEEF..GKNEEEF....X',
    'VD*EEEEEEF...D*EEJI....X',
    'VDEEE!EEJI...GKEEF..ABCX',
    'VDEEEEEEF.....D*JI..DEFX',
    'VDEEEEEEF.....GHI..AMEFX',
    'VDEEEEEEF..........DEEFX',
    'VDEEEEEEF.........AMEEFX',
    'VDEEEEEELC.....ABBMEEEF3',
    'VDEEEEENELBBBBBME$EEEELB',
    'VDNEEEEEEEEEEEEEEEEEEEE@',
    'VDEEEEEEEEEEEEEEEEEEEEJH',
    'VGKEEEEEEEEEEEEEENEEEEF1',
    'V.GHK$EEEEEEEEEEEEEEEEFX',
    'V...GHHKEEEE*EEEEEEEE*FX',
    'V......GHHHHHHHHHHHHHHIX',
    'YZZZZZZZZZZZZZZZZZZZZZZ0',
]
# Room4 TILEMAP (51x31)
ROOM_TILEMAP[4] = [
    'STTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTU',
    'V........ABBC..........9................ABBBBBC...X',
    'V.9.ABBBBM*ELBBBBBBC...................AMEE$EELC..X',
    'V..AMEEEEEOEEE$EEEELC......ABBBBC....8AMEEEEEEELC.X',
    'VABMEEEEEEEEEEEEEEEELBCABBBMEEEELBC..AMEEEEEEEEELCX',
    '4DEEEENEEEE!EEEEEEEEEELMEEEEEEEEEELBBMEEEOEEE!EE*FX',
    'BMEEEEEEEEEEEEEEEEEEEEEEEEEENEEEEEEEEEEEEEEEEEEEEFX',
    '@EEEEEEEJHHHHHHHKEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFX',
    'HKEEEEEJI.......GHKEEPE!EEEJHHHKEEEEEEEEEEEEEEPEEFX',
    '2DEEEEELC.........GKEEEEEJHI...GHHHHHKEEN!EEEEEEEFX',
    'VGKEEEEEF....8.....GKEEEEF...........GKEEEEEEEE*JIX',
    'V.DEEEE$F...........D$EE*F...ABBC.....GKEEEEEEEJI.X',
    'V.GKPEEELBBC........DEEEJI..AME$LC.....GKEEEEEJI..X',
    'V..DEEEEEEELC.......GKEEF...DEEEELC.....GKEEEJI...X',
    'V..DEEEEEEEELC.....9.DEJI...D*EEEEF......DEEELC...X',
    'V.AMEEEEE!EEELC......D*F....GKEEEELC.....DEEEEF...X',
    'V.D*EEEEEEEEENF......GHI.....GKEEE*F.....DEEEEF.9.X',
    'V.DEEEEEEEEEEELC............ABMEEPELC....GKEEEF...X',
    'V.DEEEEEEEEEEEEF...........AMEEEEEEELC....DEEELBC.X',
    'V.DEEEEEEEOEEEELC....8....AMEEEEE!EEELCABBMEEEEEF.X',
    'V.DEEE!EEEEEEEEELC.....ABBMEEEEEEEEEEELMEEEEEEEELCX',
    'V.GKEEEEEEEEEEEEELC..ABMEEEEEEEEEEEEEEEEEEEEEEEEEFX',
    'V..GKEEEEEEEEEEEEELBBMEEEEEEEEEEEEOEEEEEEEEEEEEEEFX',
    'V.9.GKEE$EEJKEEEEEEEENEEEEEEEEEEEEEEEEEEEEEEE!NE$FX',
    'V....GHHHHHIGKEEEEEEEEEEEEEEEE!EEEEEEEJHHHKEEEEEEFX',
    'V............GHHKEEEEEEEEJHKEEEEENEEEJI...DEEEEEEFX',
    'V.....9........AMEEEEEJHHI.GK*EEEEEEJI....GKEEEEEFX',
    'V..............D*ENEEEF.....GKEE$EEJI......DEEEEJIX',
    'V...........8..DEEEEEJI.9....GHHHHHI....8..GKE*EF.X',
    'V..............GKEJHHI......................GHHHI.X',
    'YZZZZZZZZZZZZZZ2D@F1ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ0',
]
# Room5 TILEMAP (70x38)
ROOM_TILEMAP[5] = [
    'STTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT4D@F3TTTTTTTTU',
    'V....................................ABBBBBBBBBC........AMELC........X',
    'V....................................DEEEEEEEEEF........DEEEF........X',
    'V....................................D$EEEEEEE$F........DEEEF........X',
    'V.........8..........................DEEEEE!EEELBBBBBBBBMEEELBBBBBC..X',
    'V............9..........9............DEEEEEEEEEEEEEEEEEEEEEEEEEEE*F..X',
    'V....................................D$EE!EEEEEEEEEEEEEPEEEEEEEEEEF..X',
    'V.8..................................DEEEEEEEEEEEEEEEEEEEEEEEEEEEEF..X',
    'V....................................DEEEEE!EEEJHHHHHHHHHHHHHHKEEEF..X',
    'V..............................ABBBC.D$EEEEEEE$F..............DEEEF..X',
    'V..............................DE*EF.DEEEEEEEEEF........8.....DEEEF..X',
    'V.....8...........8............DEEEF.GHHHHHHHHHI..............DEEEF..X',
    'V..............................DEE*F...8......................DEEEF..X',
    'V...........9..................DEEEF.................9........DEEEF..X',
    'V.ABBBBBBBBBBBBCABBBBBBBBBBBBC.D*EEF..........................DEEEF..X',
    'V.DEEEEEEPEEEEEFDEEEEEEEEEEEEF.DEEEF......ABBBBBBBBBBBBBBBBBBBMEEELC.X',
    'V.D*EEEEEEEEEEEFDEEOEEEEEEEEEF.DEEEF......DEEEEEEEEEEEEEEEENEEEEEEEF.X',
    'V.DEEEEEEEEEE!$FD$EEEEEEEE!EEF.DEEEF..9...DEEEEEEEEEEEEEEEEEEEEEEEEF.X',
    'V.DEEEEEEEEEEEEFDEEEEEEEEEEEEF.DEEEF......DEEEJKEEEEE*JKEEEEEEJKEEEF.X',
    'V.DEENEEEEEEEEEFDEEEEEEEEEEEEF.DEEEF......DEEJIGKEEEEJIGKEEEEJIGKEEF.X',
    'V.DEEEEEEEEEEEEFDEEEEEENEE*EEF.DEEEF......DEELCAMEEEELCAMEEEELCAMEEF.X',
    'V.GHHHKEEEJHHHHIGHHHKEEEJHHHHI.DEEEF......DEEELM*EEEEELMEEEEE$LMEEEF.X',
    '4ABBBBMEEELBBBBBBBBBMEEELBBBBBBMEEELBBBBBBMEE!EEEEEEEEEEEEEEEEEEEEEF.X',
    'BMEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOEEEEEF.X',
    '@EEEEEEEEPEEEEEEEEEEEEEEEEENEEEEEEEEEEEEEEEEEEEEEPEEEEEEEEEEEEEEEEEF.X',
    'HKEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE!EEEEF.X',
    '2GHHHHKEEEJHHHHHHHHHKEEEJHHHHHHKEEEJHHHHHHKEE!EEEEEEEEEEEEEEEEEEEEEF.X',
    'V.ABBBMEEELBBBBCABBBMEEELBBBBC.DEEEF......DEEEJKEEEEEEJKEEEEEEJKEEEF.X',
    'V.DEEEEEEEOEEEEFDEEEEEEEEE*EEF.DEEEF......DEEJIGKEEEEJIGKEEEEJIGKEEF.X',
    'V.DEEEEEEEEEEEEFDENEEEEEEEEEEF.DEEEF......DEELCAMEEEELCAMEEEELCAMEEF.X',
    'V.DEENEEEEEEEEEFDEEEEEEEEEEEEF.DE$EF.....8DEEELM$EEEE*LMEEEEEELMEEEF.X',
    'V.DE!EEEEEEEEE$FD$EEEEEEEEEEEF.GHHHI......DEEEEEEEEEEEEEENEEEEEEEEEF.X',
    'V.DEEEEEEEEPEEEFDEE!EEEEEEEOEF............DEEEEEEEEEEEEEEEEEEEEEEEEF.X',
    'V.DEEEE*EEEEEEEFDEEEEEEEEEEEEF..8.........GHHHHHHHHHHHHHHHHHHHHHHHHI.X',
    'V.GHHHHHHHHHHHHIGHHHHHHHHHHHHI.................................8.....X',
    'V............8..................................9....................X',
    'V9...................................................................X',
    'YZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ0',
]
# Room6 TILEMAP (40x20)
ROOM_TILEMAP[6] = [
    'STTTTTTTTTTTT4D@F3TTTTTTTTTTTTTTTTTTTTTU',
    'V...........ABMELBBC..............6....X',
    'V..6..ABBBBBMEEEEEELBBBBBBC.5..........X',
    'V.....DEENEEEEEEEEEEEENEEELBBBBC.......X',
    'V...ABMEEEEEEEEEEEEEEEEEEEEEEEELBC.....X',
    'V..AMEOEEJKEEJHK*EEEEJHHKEEEEOEEELC....X',
    'V..DEEEEJIDE!LCGHKEEEF..GHKE$EEEEELC...X',
    'V..DE!EJIAMEEELC.DEEJI....GHKEEEEEELBBC3',
    'V..DEEEF.D*EPE$F.GKEF..5....GHKEEEPEEELB',
    'V.AMOEJI6GKEEEEF..D$F.........GKEEEEEEE@',
    'V.DEEEF...GK*EJI..GHI....ABC...DEEEEEEJH',
    '4AMEEELC...GHHI....6....AM*F..AMENEEJHI1',
    'BMEEEE$F...............AMEELCAMEEEEJI..X',
    '@EEEEEELBBBBBBBBBBBBBBBME!EELMEEEEJI...X',
    'HKEEEEOEEEEEEEEEEEEEEEENEEEEEEEEEJI..6.X',
    '2GHKEEEEEEEEEEPEEEEEEEEEEEEEEEEEJI.....X',
    'V..GHHHHHHHHHHHKEEEEEEEEEJHHHHHHI......X',
    'V......6.......GHKE$EE*JHI.......6.....X',
    'V...........5....GHHHHHI...............X',
    'YZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ0',
]
# Room7 TILEMAP (45x30)
ROOM_TILEMAP[7] = [
    'STTTTTTTTTTTTTTTTTTTTTTTTT4D@F3TTTTTTTTTTTTTU',
    'V.........................AMELC.............X',
    'V..........ABBBBBBBBBBBBCAMEEELBBBBBBC......X',
    'V....ABBBBBMEE$EEEEEEEEELMEEEEEEEEE$ELBBBBC.X',
    'V....DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEF.X',
    'V....DEEEEEEEEEEEE!EEEEEEEEEEEEEEEEEEEEEEEF.X',
    'V...AMEEEEJK*EEEEEEEEEEEJKEEEEEEEEEEEJHKEEF.X',
    'V...DEEEEEFGHHHHKEEJHHHHIGHHHHHHHHHHHI.DEEF.X',
    'V...DEEEEEF.....DEEF...................DEEF.X',
    'VABBM$E!EEF.....DEEF.............ABBBBBMEELCX',
    'VD$EEEEEEEF....AMEELBBBBBBC......D*EEEEEEEEFX',
    'VDEEEEEEEEF....DEEEEEE*EEELBBBBBBMEEEEEEEEEFX',
    'VGHHKEEEEEF....DEEEEEEEEEEEEEEEEEEEEEE!EEEEFX',
    'V...DEEEE$F....DEEEE!EEEEEEEEEEEEEEEEEEEEEEFX',
    'V...DEEEEEF....DEEEEEEEEEEJHHHHHHKEEEEEEEE$FX',
    'VABBMEEEEEF....DEEEEEEEE$EF......DEEEEEEEEEFX',
    'VD*EEEE!EEF....GHHKEEJHHHHI......GHKEEJHHHHIX',
    'VDEEEEEEEEF.......DEEF..........ABBMEELBC...X',
    'VDEE*EEEEEF.......DEEF..........DEEEEEEEF...X',
    'VGHHHHKEEJI.......DEEF..........DEEEEEEELBBC3',
    'V.....DEEF........DEEF..........D$EEJKEEEEELB',
    'V.....DEEF.ABBBBBBMEELBC.ABBBBBBMEEEFDEEEEEE@',
    'V.ABBBMEELBMEE*EEEEEEEEF.DEEEEEEEEEELMEEEEEJH',
    'V.DEEEEEEEEEEEEEEEEEEEEF.DEEEEEEEEEEEEEEJHHI1',
    'V.DEEEEEEEEEEEEEEEEEEEELBMEEJHHHKEEEEEE*F...X',
    'V.DEEJHHHHHKEEEEE!EEEEEEEEEEF...GHHHHHHHI...X',
    'V.D$EF.....DEEEEEEEEEEEEEEEEF...............X',
    'V.GHHI.....DEE$EEEEEEEEJHHHHI...............X',
    'V..........GHHHHHHHHHHHI....................X',
    'YZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ0',
]
# Room8 TILEMAP (50x40)
ROOM_TILEMAP[8] = [
    'STTTTT4D@F3TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTU',
    'V.....AMELC.........ABBBBBBC.....................X',
    'V.....DEEELC.......AME*EE$ELC....................X',
    'V....AMEEEEF......AMEEEEEEEELC...........ABBC....X',
    'V...AMEEEEELBBBBBBMEEEEEEEEEELBBBBBBBBBBBME$LC...X',
    'V...DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEF...X',
    'V...D$EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE!EEEEEJI...X',
    'V...DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEJHI....X',
    'V...DEEEEEJHHHHHHKEEEEEEEEEEEEEJHHHHKEEEJHI......X',
    'V...GHHKEELBC....GKEEEEEEEEEEEJI....GKEEF........X',
    'V.....AMEEEELBC...DEEEEEEEEEEJI......DEELC.......X',
    'V....AMEEEEEEEF...GK*EEE!EEE*F.......DEEEF.......X',
    'V....DEEEEEEEEF....DEEEEEEEEEF.......DEEELC......X',
    'V..ABMEEEEEEEJI....GKEEEEEEEEF.......DEEEEF......X',
    'V.AMEEEEEEEJHI......DEEEEEEEJI.......GKEEEF......X',
    'V.DEEEEEEEJI........GK*EEEEJI.........DEEEF......X',
    'V.DEEEEEJHI..........GKE$EJI..........DEEELC.....X',
    'V.DEE!EJI....ABBBBC...GHHHI...........GKEEEF.....X',
    'V.DEEEEF....AME$EELC...................DEEEF.....X',
    'V.DEEEEF...AM*EEEEELC.......ABBBBC.....DEEEF.....X',
    'V.DEEEJI..AMEEEEEEEELC....ABMEEEELC....DEEELC....X',
    'V.DEEEF...DEEEEEEEEEEF..ABMEEEEEEELBBC.DEEEEF....X',
    'V.DEEEF...D*EEEEEEEE$F.AMEEEEEE!EEEEELCGKEEELC...X',
    'V.DEEJI...DEEEE!EEEEEF.DEEEEEEEEEEEEEELBMEEEELBBC3',
    'V.DEEF....GK$EEEEEEEEF.DEEEEEJHHHKEEEEEEEEEEEEEELB',
    'V.DEEF.....GKEEEEEEEJI.D$EEEJI...GHHKEEEEEEEEEEEE@',
    'V.DEEF......GKEEEEEEF..DEEE*F.......GHHHKEEEEEEEJH',
    'V.DEEF.......GKEEEEJI..GKEEJI...........D$EEEJHHI1',
    'V.DEELC......AMEEEEF....GHHI..........ABMEEEJI...X',
    'V.DEEELC....AMEEEEELC................AMEEEEEF....X',
    'V.DEEEELC.ABMEEEEEEEF...............AMEEEEEJI....X',
    'V.GKEEEELBM*EEEEEEEELBBC.........ABBMEEEEEEF.....X',
    'V..GKEEEEEEEEEEEEEEEEEELBBBBBBBBBMEEEEEEEEJI.....X',
    'V...D$EEEEEEEEEEEEEEEEEEEEEEEEE!EEEEEEEEJHI......X',
    'V...GHKEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEJHI........X',
    'V.....GKEEEEEEEEEEEEEEEJHHHHHHHHHHHHHHI..........X',
    'V......GHHHHHKEEEJHHHHHI.........................X',
    'V............DEEEF...............................X',
    'V............GKEJI...............................X',
    'YZZZZZZZZZZZZ2D@F1ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ0',
]